(function (undefined) {

    /* As for 31.03.16, Instant Translate Browsers supports:
     * 104 languages + auto
     */

    pl.extend(ke.ext.const.lang, {
        list: {
            'Auto': 'auto',
            'Afrikaans': 'af',
            'Albanian': 'sq',
            'Arabic': 'ar',
            'Armenian': 'hy',
            'Azerbaijani': 'az',
            'Basque': 'eu',
            'Belarusian': 'be',
            'Bengali': 'bn',
            'Bosnian': 'bs',
            'Bulgarian': 'bg',
            'Catalan': 'ca',
            'Cebuano': 'ceb',
            'Chichewa': 'ny',
            'ChineseSimplified': 'zh-CN',
            'ChineseTraditional': 'zh-TW',
            'Croatian': 'hr',
            'Czech': 'cs',
            'Danish': 'da',
            'Dutch': 'nl',
            'English': 'en',
            'Esperanto': 'eo',
            'Estonian': 'et',
            'Filipino': 'tl',
            'Finnish': 'fi',
            'French': 'fr',
            'Galician': 'gl',
            'Georgian': 'ka',
            'German': 'de',
            'Greek': 'el',
            'Gujarati': 'gu',
            'HaitianCreole': 'ht',
            'Hausa': 'ha',
            'Hebrew': 'iw',
            'Hindi': 'hi',
            'Hmong': 'hmn',
            'Hungarian': 'hu',
            'Icelandic': 'is',
            'Igbo': 'ig',
            'Indonesian': 'id',
            'Irish': 'ga',
            'Italian': 'it',
            'Javanese': 'jw',
            'Japanese': 'ja',
            'Kannada': 'kn',
            'Kazakh': 'kk',
            'Khmer': 'km',
            'Korean': 'ko',
            'Lao': 'lo',
            'Latin': 'la',
            'Latvian': 'lv',
            'Lithuanian': 'lt',
            'Macedonian': 'mk',
            'Malagasy': 'mg',
            'Malay': 'ms',
            'Maltese': 'mt',
            'Maori': 'mi',
            'Marathi': 'mr',
            'Mongolian': 'mn',
            'Nepali': 'ne',
            'Norwegian': 'no',
            'Persian': 'fa',
            'Polish': 'pl',
            'Portuguese': 'pt',
            'Punjabi': 'pa',
            'Romanian': 'ro',
            'Russian': 'ru',
            'Serbian': 'sr',
            'Sesotho': 'st',
            'Sinhala': 'si',
            'Slovak': 'sk',
            'Slovenian': 'sl',
            'Somali': 'so',
            'Spanish': 'es',
            'Sundanese': 'su',
            'Swahili': 'sw',
            'Swedish': 'sv',
            'Tajik': 'tg',
            'Tamil': 'ta',
            'Telugu': 'te',
            'Thai': 'th',
            'Turkish': 'tr',
            'Ukrainian': 'uk',
            'Urdu': 'ur',
            'Uzbek': 'uz',
            'Vietnamese': 'vi',
            'Welsh': 'cy',
            'Yiddish': 'yi',
            'Yoruba': 'yo',
            'Zulu': 'zu',
            'Malayalam': 'ml',
            'MyanmarBurmese': 'my',

            // v2.9.46 (+13 langs)

            'Amharic': 'am',
            'Corsican': 'co',
            'Frisian': 'fy',
            'Hawaiian': 'haw',
            'KurdishKurmanji': 'ku',
            'Kyrgyz': 'ky',
            'Luxembourgish': 'lb',
            'Pashto': 'ps',
            'Samoan': 'sm',
            'ScotsGaelic': 'gd',
            'Shona': 'sn',
            'Sindhi': 'sd',
            'Xhosa': 'xh'
        }
    })

})();